service: sentinel-tiler

provider:
  name: aws
  runtime: python3.6
  stage: production

  region: eu-central-1

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:ListBucket"
       - "s3:GetObject"
     Resource:
       - "arn:aws:s3:::sentinel-s2-l1c*"

  environment:
    GDAL_DATA: /var/task/share/gdal # NEEDED IF CUSTOM GDAL
    GDAL_CACHEMAX: 75%
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 536870912
    GDAL_DISABLE_READDIR_ON_OPEN: true
    AWS_REQUEST_PAYER: "requester"
    CPL_VSIL_CURL_ALLOWED_EXTENSIONS: ".jp2,.ovr"

  #Optional Bucket where you store your lambda package
  # deploymentBucket: {YOUR BUCKET}

custom:
  apigwBinary:
    types:
      - '*/*'
  contentEncoding:
    minimumCompressionSize: 0

plugins:
  - serverless-content-encoding
  - serverless-apigw-binary

package:
  artifact: package.zip

functions:
  sentinel-tiler:
    handler: app.sentinel.APP
    memorySize: 1536
    timeout: 20
    events:
      - http:
          path: sentinel/{proxy+}
          method: get
          cors: true
